import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "@/Components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kanban Dashboard Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex justify-end items-start w-full`}
      >
        {/* sidebar container */}
        <div className="w-[18%] fixed left-0 flex justify-start items-start h-screen overflow-hidden">
          <SideBar />
        </div>

        {/* content container */}
        <div className="w-[82%] flex flex-col justify-start items-start h-full overflow-x-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
